"""initial schema

Revision ID: 95fb7080056c
Revises: 
Create Date: 2026-07-27 05:36:23.033842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fb7080056c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('guest_link_expiry_days', sa.Integer(), nullable=False),
    sa.Column('seq_trip', sa.Integer(), nullable=False),
    sa.Column('seq_group', sa.Integer(), nullable=False),
    sa.Column('seq_booking', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('airlines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('travel_classes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_tenant_id'), 'airlines', ['tenant_id'], unique=False)
    op.create_table('currencies',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_tenant_id'), 'currencies', ['tenant_id'], unique=False)
    op.create_table('drivers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.create_table('guests',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('membership_no', sa.String(length=60), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('passport_no', sa.String(length=40), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('visa_status', sa.String(length=40), nullable=True),
    sa.Column('additional_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_tenant_id'), 'guests', ['tenant_id'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('room_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_tenant_id'), 'hotels', ['tenant_id'], unique=False)
    op.create_table('marketing_agents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_agents_tenant_id'), 'marketing_agents', ['tenant_id'], unique=False)
    op.create_table('packages',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_tenant_id'), 'packages', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'MARKETING', 'COORDINATOR', 'RESERVATIONS', 'TRANSPORT', 'FNB_VIEW', 'MANAGER', name='user_role'), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role', 'permission_id')
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('flight_amber_days', sa.Integer(), nullable=False),
    sa.Column('flight_red_hrs', sa.Integer(), nullable=False),
    sa.Column('hotel_amber_days', sa.Integer(), nullable=False),
    sa.Column('hotel_red_hrs', sa.Integer(), nullable=False),
    sa.Column('visa_amber_days', sa.Integer(), nullable=False),
    sa.Column('visa_red_hrs', sa.Integer(), nullable=False),
    sa.Column('pickup_amber_hrs', sa.Integer(), nullable=False),
    sa.Column('pickup_red_hrs', sa.Integer(), nullable=False),
    sa.Column('drop_amber_hrs', sa.Integer(), nullable=False),
    sa.Column('drop_red_hrs', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('transport_vendors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=True),
    sa.Column('vehicle_types_offered', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_vendors_tenant_id'), 'transport_vendors', ['tenant_id'], unique=False)
    op.create_table('visa_fee_guides',
    sa.Column('nationality_group', sa.String(length=120), nullable=False),
    sa.Column('fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_fee_guides_tenant_id'), 'visa_fee_guides', ['tenant_id'], unique=False)
    op.create_table('guest_preferences',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('dietary', sa.String(length=200), nullable=True),
    sa.Column('beverage', sa.String(length=200), nullable=True),
    sa.Column('room', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('vip_level', sa.String(length=80), nullable=True),
    sa.Column('signboard_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id')
    )
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'MARKETING', 'COORDINATOR', 'RESERVATIONS', 'TRANSPORT', 'FNB_VIEW', 'MANAGER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_mark_paid', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['marketing_agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('vehicle_no', sa.String(length=80), nullable=False),
    sa.Column('vehicle_type', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'MARKETING', 'COORDINATOR', 'RESERVATIONS', 'TRANSPORT', 'FNB_VIEW', 'MANAGER', name='user_role'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('trip_groups',
    sa.Column('group_no', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'group_no')
    )
    op.create_index(op.f('ix_trip_groups_tenant_id'), 'trip_groups', ['tenant_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('trips',
    sa.Column('trip_no', sa.String(length=60), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CLEARED', 'BOOKING', 'TRAVEL_CONFIRMED', 'IN_HOUSE', 'COMPLETED', 'CLOSED', 'CANCELLED', 'NO_SHOW', name='trip_status'), nullable=False),
    sa.Column('package_flag', sa.Enum('PENDING', 'QUALIFIED', 'NOT_QUALIFIED', name='package_flag_status'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('departure_date >= arrival_date', name='ck_trip_dates_order'),
    sa.ForeignKeyConstraint(['agent_id'], ['marketing_agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['trip_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'trip_no')
    )
    op.create_index(op.f('ix_trips_tenant_id'), 'trips', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('note_type', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_trip_id'), 'audit_events', ['trip_id'], unique=False)
    op.create_table('companions',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('passport_no', sa.String(length=40), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('visa_status', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companions_tenant_id'), 'companions', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('owner_type', sa.Enum('guest', 'companion', 'booking', 'visa', 'other', name='document_owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('passport', 'visa', 'invoice', 'eta', 'other', name='document_category'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('expense_summaries',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('flight_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hotel_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transport_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('visa_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_total_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'version')
    )
    op.create_index(op.f('ix_expense_summaries_tenant_id'), 'expense_summaries', ['tenant_id'], unique=False)
    op.create_table('flight_bookings',
    sa.Column('booking_no', sa.String(length=60), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('guest', 'group', name='booking_level'), nullable=False),
    sa.Column('airline_id', sa.UUID(), nullable=True),
    sa.Column('airline_name', sa.String(length=200), nullable=False),
    sa.Column('travel_class', sa.String(length=60), nullable=False),
    sa.Column('flight_numbers', sa.String(length=120), nullable=False),
    sa.Column('pnr', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=120), nullable=True),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('Pending', 'Paid', 'Partially Paid', 'Outstanding', name='payment_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('booking_status', sa.Enum('Draft', 'Confirmed', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('cancellation_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancellation_charge_lkr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(trip_id IS NOT NULL) OR (group_id IS NOT NULL)', name='ck_flight_owner'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['trip_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'booking_no')
    )
    op.create_index(op.f('ix_flight_bookings_tenant_id'), 'flight_bookings', ['tenant_id'], unique=False)
    op.create_table('guest_share_links',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_share_links_tenant_id'), 'guest_share_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_guest_share_links_token_hash'), 'guest_share_links', ['token_hash'], unique=True)
    op.create_table('hotel_bookings',
    sa.Column('booking_no', sa.String(length=60), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('guest', 'group', name='booking_level'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('room_type', sa.String(length=120), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('night_count', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('confirmation_no', sa.String(length=60), nullable=True),
    sa.Column('meal_plan', sa.String(length=20), nullable=True),
    sa.Column('rate_per_night', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('Pending', 'Paid', 'Partially Paid', 'Outstanding', name='payment_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('booking_status', sa.Enum('Draft', 'Confirmed', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('cancellation_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancellation_charge_lkr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(trip_id IS NOT NULL) OR (group_id IS NOT NULL)', name='ck_hotel_owner'),
    sa.CheckConstraint('check_out > check_in', name='ck_hotel_dates_order'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['trip_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'booking_no')
    )
    op.create_index(op.f('ix_hotel_bookings_tenant_id'), 'hotel_bookings', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'MARKETING', 'COORDINATOR', 'RESERVATIONS', 'TRANSPORT', 'FNB_VIEW', 'MANAGER', name='notification_role'), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('package_qualification_flags',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUALIFIED', 'NOT_QUALIFIED', name='package_flag_status'), nullable=False),
    sa.Column('set_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_qualification_flags_tenant_id'), 'package_qualification_flags', ['tenant_id'], unique=False)
    op.create_table('transport_legs',
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('guest', 'group', name='booking_level'), nullable=False),
    sa.Column('leg_type', sa.Enum('Arrival Pickup', 'Hotel–Casino Transfer', 'Departure Drop', 'Other', name='transport_leg_type'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('inhouse', 'vendor', name='transport_source'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_vehicle_type', sa.String(length=80), nullable=True),
    sa.Column('usage_type', sa.Enum('Airport', 'City use', 'Out-of-city', 'Multi-day', name='usage_type'), nullable=True),
    sa.Column('rate_basis', sa.Enum('Per trip', 'Per day', 'Per km', name='rate_basis'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('lkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('Pending', 'Paid', 'Partially Paid', 'Outstanding', name='payment_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('destination_notes', sa.String(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('cancel_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source = 'inhouse' AND vehicle_id IS NOT NULL AND vendor_id IS NULL) OR (source = 'vendor' AND vendor_id IS NOT NULL AND vehicle_id IS NULL)", name='ck_leg_source_consistency'),
    sa.CheckConstraint('(trip_id IS NOT NULL) OR (group_id IS NOT NULL)', name='ck_leg_owner'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['trip_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['transport_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leg_vehicle_time', 'transport_legs', ['vehicle_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_transport_legs_tenant_id'), 'transport_legs', ['tenant_id'], unique=False)
    op.create_table('trip_checklist_items',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.Enum('flight', 'hotel', 'visa', 'pickupA', 'pickupC', 'dropA', 'dropC', 'expense', 'flag', name='checklist_item_key'), nullable=False),
    sa.Column('is_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('na_reason', sa.String(), nullable=True),
    sa.Column('na_by', sa.UUID(), nullable=True),
    sa.Column('na_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['na_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'item_key')
    )
    op.create_index(op.f('ix_trip_checklist_items_tenant_id'), 'trip_checklist_items', ['tenant_id'], unique=False)
    op.create_table('trip_clearances',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('cleared_by_name', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_clearances_tenant_id'), 'trip_clearances', ['tenant_id'], unique=False)
    op.create_table('trip_handovers',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_handovers_tenant_id'), 'trip_handovers', ['tenant_id'], unique=False)
    op.create_table('trip_notes',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.Enum('General', 'Error & Correction', 'Incident', 'Guest Feedback', name='note_type'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_notes_tenant_id'), 'trip_notes', ['tenant_id'], unique=False)
    op.create_table('visa_applications',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('traveller_type', sa.Enum('guest', 'companion', name='visa_traveller_type'), nullable=False),
    sa.Column('traveller_ref_id', sa.UUID(), nullable=False),
    sa.Column('traveller_name', sa.String(length=200), nullable=False),
    sa.Column('passport_no', sa.String(length=40), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('Not Required', 'To Apply', 'Applied', 'Granted', 'Rejected', 'On Arrival', name='visa_status'), nullable=False),
    sa.Column('eta_reference', sa.String(length=80), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('fee_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('Pending', 'Paid', 'Partially Paid', 'Outstanding', name='payment_status'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'traveller_ref_id')
    )
    op.create_index(op.f('ix_visa_applications_tenant_id'), 'visa_applications', ['tenant_id'], unique=False)
    op.create_table('expense_summary_items',
    sa.Column('expense_summary_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('Flight', 'Hotel', 'Transport', 'Visa', name='expense_category'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('is_shared_group', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expense_summary_id'], ['expense_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_link_access_log',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['guest_share_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_link_access_log')
    op.drop_table('expense_summary_items')
    op.drop_index(op.f('ix_visa_applications_tenant_id'), table_name='visa_applications')
    op.drop_table('visa_applications')
    op.drop_index(op.f('ix_trip_notes_tenant_id'), table_name='trip_notes')
    op.drop_table('trip_notes')
    op.drop_index(op.f('ix_trip_handovers_tenant_id'), table_name='trip_handovers')
    op.drop_table('trip_handovers')
    op.drop_index(op.f('ix_trip_clearances_tenant_id'), table_name='trip_clearances')
    op.drop_table('trip_clearances')
    op.drop_index(op.f('ix_trip_checklist_items_tenant_id'), table_name='trip_checklist_items')
    op.drop_table('trip_checklist_items')
    op.drop_index(op.f('ix_transport_legs_tenant_id'), table_name='transport_legs')
    op.drop_index('ix_leg_vehicle_time', table_name='transport_legs')
    op.drop_table('transport_legs')
    op.drop_index(op.f('ix_package_qualification_flags_tenant_id'), table_name='package_qualification_flags')
    op.drop_table('package_qualification_flags')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_hotel_bookings_tenant_id'), table_name='hotel_bookings')
    op.drop_table('hotel_bookings')
    op.drop_index(op.f('ix_guest_share_links_token_hash'), table_name='guest_share_links')
    op.drop_index(op.f('ix_guest_share_links_tenant_id'), table_name='guest_share_links')
    op.drop_table('guest_share_links')
    op.drop_index(op.f('ix_flight_bookings_tenant_id'), table_name='flight_bookings')
    op.drop_table('flight_bookings')
    op.drop_index(op.f('ix_expense_summaries_tenant_id'), table_name='expense_summaries')
    op.drop_table('expense_summaries')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_companions_tenant_id'), table_name='companions')
    op.drop_table('companions')
    op.drop_index(op.f('ix_audit_events_trip_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_trips_tenant_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_trip_groups_tenant_id'), table_name='trip_groups')
    op.drop_table('trip_groups')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('guest_preferences')
    op.drop_index(op.f('ix_visa_fee_guides_tenant_id'), table_name='visa_fee_guides')
    op.drop_table('visa_fee_guides')
    op.drop_index(op.f('ix_transport_vendors_tenant_id'), table_name='transport_vendors')
    op.drop_table('transport_vendors')
    op.drop_table('tenant_settings')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_packages_tenant_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_marketing_agents_tenant_id'), table_name='marketing_agents')
    op.drop_table('marketing_agents')
    op.drop_index(op.f('ix_hotels_tenant_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_guests_tenant_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_currencies_tenant_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_airlines_tenant_id'), table_name='airlines')
    op.drop_table('airlines')
    op.drop_table('tenants')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
